Add import pluginplay back
Although `pluginplay` is not used, `import pluginplay` is required otherwise you get
```bash
TypeError: Unregistered type : pluginplay::ModuleInput
```

This is not expected and can create annoying problems.